@startuml


abstract class Actor
class User
class Attachment


Actor <|-- User
Attachment *- User

enum TimeUnit {
DAYS
HOURS
MINUTES
}

abstract Actor{
-id
-name
-sex
-age
-email
-phone
-cardNum
-address
-sysdate
}

class Attachment{
-id
-path
-type
-sysdate
}

class User {
-id
-username
-password
-isValid
-level
-lastLoginTime
-Attachment
-registerTime
-image
}

User*-*level


class level{
-id,
-point
-description
}
Point*-*level
class Point{
-id
-count
}

User *-* userConfig
class userConfig{
-id
-User
-configJson
}

class organization{
-id
-name
-state
-description
-image
}

stick*-*organization
stick*-*User
class stick{
-id
-title
-subTitle
-content
-User
-state
-organization
-sendTime
-parentId
}

User *-* image
organization *-* image
class image{
-id
-description
-path
-updateTime
-state
}







@enduml